# Partial Fraction Decomposition 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal as sig

First we define the numerator and denominator polynomials of the Laplace equations

In [2]:
nb = np.array([1])
nap = np.array([1,2,2])
nas = np.array([1,2,2,0])
pfdap = sig.residue(nb,nap)
pfdas = sig.residue(nb,nas)

In [3]:
pfdap

(array([0.-0.5j, 0.+0.5j]),
 array([-1.+1.j, -1.-1.j]),
 array([], dtype=float64))

In [4]:
pfdas

(array([ 0.5 +0.j  , -0.25+0.25j, -0.25-0.25j]),
 array([ 0.+0.j, -1.+1.j, -1.-1.j]),
 array([], dtype=float64))